version: "3.3"
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb
    volumes:
      - ./tmp/localstack/data:/tmp/localstack/data
